### ISSUE TITLE
Modelling of forces in milling

### ISSUE THREAD

**Issue by koeri246** [WBK-Robotics/pybullet_industrial#27]
**Is your feature request related to a problem? Please describe.**
In order to simulate milling processes one needs to take the ocurring forces into account. <br>For that purpose a model for the calculation of forces that act on the endeffector tool would be needed.

**Describe the solution you'd like**
Ideally the calculation would require as few information as possible. Some general variables would be rotational speed $n$ and feed speed $v_f$, tool diameter $d$, number of tooths $z$, cutting depth $a_p$, etc. One would need to collect a handful of coefficients for different materials of the cutting edges and of the workpiece. <p>

**Calculation of the cutting force**
The forces in milling can be seperated in a radial and a tangential component. <br>The tangential component, known as the cutting force, is usually calculated per tooth. 
Depending on the number of tooths in contact and their orientation a resultant force can be calculated. Forces normal to the workpiece surface are generally not considered.</p>
There are two models being referenced in literature quite often:

1) Exponential Approach by Kienzle ([1] and [2]):
	
	The main contributor to the cutting force is the chip thickness $h$. The associated area $A=a_p \cdot h$. <br>When the edges of the tooth are straight, the chip thickness approximates the feed per tooth $h\approx f_z$, with
	
	$f_z=\frac{v_F}{n \cdot z}$.
	Otherwise the tilt of the tooth edge must be considered.
	The cutting force per tooth is calculated by
	
	$F_c=k_c \cdot A \cdot C_1 \cdot C_2$,
	
	where $k_c$ is a paramater representing the material pairing of tool and workpiece using a specific base cutting force $k_{c1.1}$. The specific force is
	
	$k_c=\frac{k_{c1.1}}{h^{m_c}}$ with $h =0,1 ... 1,0  \mathrm{mm}$. Depending on $h$, $k_c$ varies [2].
	
	This model assumes an exponential relationship between the force and the chip thickness.
	$C_1$ and $C_2$ are correctioning factors for considering e.g. tool weardown and tool material. Those three parameters can be looked up in literature, e.g. in [1].<br>

	A possible calculation of the resulting force on the endeffector tool would be to consider each tooth's orientation and calculate the sum of the respective force vectors.

2) Linear approach by Altintas ([3] and [4])
	
	$F_r=K_{cr} \cdot a_p \cdot h + K_{er} \cdot a_p$<br> $F_t=K_{ct} \cdot a_p \cdot h + K_{et} \cdot a_p$
	
	In this model the chip thickness h has a linear relationship to the acting forces. The coefficients depend on a multitude of geometrical dimensions of the tooth and are calculated in quite lengthy formulas. They are not listed here for the sake of brevity, but are detailled in [3].

I would suggest using the former model since it is way more simpler than the latter, while being as frequently used in literature. It can be generalized for different tools, without knowing their specific dimensions and shapes, e.g. by modelling the tool as a cylinder with a certain diameter and number of tooth.
The required material constants can be looked up easily, with fewer information required. 

**Additional context**

![Groessen_fraesen](https://user-images.githubusercontent.com/107420832/184542587-8fa1ae73-5645-4ce6-bfb7-1ae0078db8a3.PNG)

![Korrekturfaktoren](https://user-images.githubusercontent.com/107420832/184542613-02192d6a-7d17-446a-b599-46e925f59dc1.PNG)

![spezif_Schnittkraft](https://user-images.githubusercontent.com/107420832/184542601-7c3b6c35-a0e7-4466-8eab-74efa0d0ba3c.PNG)

**Literature**
[1] Fischer, Ulrich, and Karl Eberscheg. Tabellenbuch Metall. Verlag Europa-Lehrmittel Nourney, Vollmer, 2008. <br>
[2] König, Wilfried. Fertigungsverfahren 1: Drehen, Fräsen, Bohren. Springer-Verlag, 2008.<br>
[3] Altintas, Y. "Modeling approaches and software for predicting the performance of milling operations at MAL-UBC." Machining science and technology 4.3 (2000): 445-478.<br>
[4] Abele, E. Wechselwirkungen von Fräsprozess und Maschinenstruktur am Beispiel des Industrieroboters. In: wt Werkstattstechnik online, 98 (9), S. 733-737. Springer-VDI-Verlag

**Comment by liquidcronos** [comment]
I agree that we should use the first force model for milling
