### ISSUE TITLE
[JOSS REVIEW] Paper feedback

### ISSUE THREAD

**Issue by sea-bass** [WBK-Robotics/pybullet_industrial#40]
Review thread at : https://github.com/openjournals/joss-reviews/issues/5174

Great job submitting Pybullet_industrial to JOSS -- I had fun trying it out. This issue captures my feedback on your paper submission.

# High-level comments
## Overall
* The paper title stylizes your tool as "Pybullet Industrial", but both the body of the text and this repo does "Pybullet_industrial". Furthermore, PyBullet is officially stylized with a capital B. So I think all the resources should reflect that and consistently use "PyBullet_industrial".
* The citation count seems a bit low, but I have some suggestions throughout this review.
* I think after the "References" section, you could stand to add more content showing actual examples of your tool in action. It's great that you have listed all the features of Pybullet_industrial, but most papers have something akin to an "Experiments" section. Make sure you include screenshots of some of your key examples, whether they are the ones shipping in the repo itself, or maybe some of the ways you have used the tool for your actual research. Bonus points if you link to some animations/videos as well.
* Finally, you should also minimally include a Conclusion section that summarizes your work and its significance, and outlines some directions of future work you are considering and/or actively working on.

## Summary
* It would be helpful to provide some more detail here, even if a sentence or two, describing what is a "process simulation". Do you mean manufacturing processes? Since the reference count is low, maybe this is an opportunity to throw in a reference here as well.
* Add a citation for G-code interpolation. Maybe consider something like [this reference](https://www.nist.gov/publications/nist-rs274ngc-interpreter-version-3) and include the term RS274 which is the official standard name? You may also want to explicitly call out your supported linear, arc, and spline capabilities.

## Overview
* In "Robot Objects" section, could you expand more on what the convenient interfaces involve? What are you using for forward/inverse kinematics, and is there room for citations of those methods? You could also cite URDF itself with e.g. [this](https://cs.paperswithcode.com/paper/understanding-urdf-a-survey-based-on-user). 
* In "Endeffector Tools", consider citing ray casting with [the original paper](https://www.sciencedirect.com/science/article/abs/pii/0146664X82901691?via%3Dihub)
* You should absolutely talk about the Extruder and Finger Gripper objects in the paper as well! I found them later in the docs and they are a key part of your work!

---

# Grammar/typos
## General
* Wherever you mention Python, make sure it is upper-case P
* Wherever you mention PyBullet, make sure it is upper-case P and B
* You should replace "endeffector" with "end effector" throughout the paper 

## Statement of Need
* Missing space between webots and the citation
*  "Pybullet_industrial is thus the first process-aware robot simulation platform build for research." --> "built for research"
* In the bulleted list, you mix conjugation "Designing, Design, Check". Either do "Design, Design, Check" or "Designing, Designing, Checking"

**Comment by liquidcronos** [comment]
Hey @sea-bass, thank you for the thorough review.
I have tried to address these in the latest commit on the paper branch. However, I am a bit confused about the missing Grippers and Extruder since both are mentioned in the paper. Do you mean that I should emphasize them more?

**Comment by sea-bass** [comment]
Thanks for the quick addressing of the reviews @liquidcronos!

> Do you mean that I should emphasize them more?

Yes. You added a citation and figure for `MillingTool`, and it would be really nice to at least have the same for the `Extruder`. The parallel gripper is maybe less important since many other simulators already handle standard rigid-body contacts.

**Comment by liquidcronos** [comment]
Hey @sea-bass , thanks for the clarification.
I have now added a section delving deeper into the working of the end effector.
I have also revised the introduction of the end effector class since this this seems to have caused some confusion. 
While the library provides geometry files for possible EndeffectorTools, these are independent of the Extruder, MillingTool, etc... 
This means that I can not show an image of the tool.

I hope the new version of the paper makes this more clear.

Let me know if the paper is now to your satisfaction!

**Comment by sea-bass** [comment]
@liquidcronos Thanks for going through these comments. It's looking great!

Just a few more comments.

## Important:
* Figure 1 doesn't show up in the latest proof. Please check this.
* My comment on adding an Examples section wasn't to add a code snippet -- actually, I don't think this is appropriate for this kind of paper. I meant to have a section between your Overview and Conclusion that describes the "real" applications that you have achieved with PyBullet Industrial. Can you describe some of the kinds of examples you have in the repo, and also maybe what you or others have achieved with this tool in your research? If you can, you should include at least one screenshot of the full PyBullet Industrial window running your favorite example, and also cite any publication(s) you or others have that use this software!

## Editorial
* The first bullet in the "Statement of Need" list is missing a full stop (".") at the end.
* First sentence in "Robot Objects": PyBullets URDF -> PyBullet's URDF
* Figure 3 looks really big
* Your "Conclusion:" header is the only header with a semicolon (:) at the end of it. Please remove it.

**Comment by liquidcronos** [comment]
Thank you for the great feedback!

Especially the clarification regarding the example, this makes much more sense.
I have included two applications which are  currently being developed using our library. Unfortunately i can not add citations for these projects as the manuscripts for their respective first publications are not yet finished.  Let me know if there is anything else i can do to improve the paper!

**Comment by sea-bass** [comment]
Thank you!

The Example Research Applications section is a little shorter than I anticipated, but it's the right content I had in mind. I still think it would be nice for this section to have a screenshot showing the **full** PyBullet Industrial GUI window with a robot in an industrial-looking background, etc. vs. the simple trajectory in Figure 5. You just need to open up your favorite example from the actual repo and take a screenshot.

Anyways, the paper is in good shape. My only requirement is that your new section appear before Conclusion, as this should be the last section before references. After that and anything else you'd like to add, I'll approve the review!

**Comment by liquidcronos** [comment]
Hey @sea-bass,
thanks for the quick reply!
I have now included a screenshot and moved the section infront of the conclusion.

**Comment by sea-bass** [comment]
Your new Figure 1 is great.

Thank you for going through this feedback, and for your work on this software + the JOSS submission. I look forward to seeing this published.
