### ISSUE TITLE
Interpolate Orientations

### ISSUE THREAD

**Issue by MaHajo** [WBK-Robotics/pybullet_industrial#47]
**Is your feature request related to a problem? Please describe.**
The current implementation of iterpolators only interpolates between positions, an aditional interpolation between orientations would be useful.

**Describe the solution you'd like**
Additional implementation of orientational interpolators.

**Describe alternatives you've considered**
Current interpolators could be reworked, however this might lead to backward copatibility issues

**Comment by philipp1604** [comment]
@MaHajo new pull request for this topic was created

**Comment by liquidcronos** [comment]
closed with pull request #51
